#ifndef CLASS_DISABLED_HASH_LIST_SIZE
#define CLASS_DISABLED_HASH_LIST_SIZE 200
#endif

#ifndef FUNC_DISABLED_HASH_LIST_SIZE
#define FUNC_DISABLED_HASH_LIST_SIZE 200
#endif

#ifndef SVIPC_PAK_MAX_SIZE
#define SVIPC_PAK_MAX_SIZE TRACE_STR_MAX_SIZE
#endif

#ifndef CLASS_NAME_MAX_SIZE
#define CLASS_NAME_MAX_SIZE 40
#endif

#ifndef FUNC_NAME_MAX_SIZE
#define FUNC_NAME_MAX_SIZE 20
#endif

#ifndef OPTS_STR_MAX_SIZE
#define OPTS_STR_MAX_SIZE 240
#endif


#ifndef FUNCTION_PROF_LIST_SIZE
#define FUNCTION_PROF_LIST_SIZE 512
#endif

#ifndef URI_REQUEST_ENABLED_PARM_ON
#define URI_REQUEST_ENABLED_PARM_ON "pulseflowswitch=on"
#endif

#ifndef URI_REQUEST_ENABLED_PARM_OFF
#define URI_REQUEST_ENABLED_PARM_OFF "pulseflowswitch=off"
#endif
